"""initial

Revision ID: d93bad49deb0
Revises: 
Create Date: 2025-11-21 15:38:27.313625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd93bad49deb0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
                    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
                    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('activity_id_seq'::regclass)"),
                              autoincrement=True, nullable=False),
                    sa.ForeignKeyConstraint(['parent_id'], ['activity.id'], name='activity_parent_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='activity_pkey'),
                    sa.UniqueConstraint('title', name='activity_title_key', postgresql_include=[],
                                        postgresql_nulls_not_distinct=False),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('building',
                    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
                    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('building_id_seq'::regclass)"),
                              autoincrement=True, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='building_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('organisation',
                    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
                    sa.Column('phone', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
                    sa.Column('building_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('activity_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'],
                                            name=op.f('organisation_activity_id_fkey')),
                    sa.ForeignKeyConstraint(['building_id'], ['building.id'],
                                            name=op.f('organisation_building_id_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f('organisation_pkey')),
                    sa.UniqueConstraint('phone', name=op.f('organisation_phone_key'), postgresql_include=[],
                                        postgresql_nulls_not_distinct=False),
                    sa.UniqueConstraint('title', name=op.f('organisation_title_key'), postgresql_include=[],
                                        postgresql_nulls_not_distinct=False)
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organisation')
    op.drop_table('building')
    op.drop_table('activity')
    # ### end Alembic commands ###
